signature/pasign/pasign/urls.py
from django.contrib import admin
from django.urls import path
from app.views import (LandingPageView, LoginPageView, DashboardView, ForgotPassView, TestView, UploadView, register_user, get_student_data)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(landing_page='index.html'), name='landing_page'),
    path('login/', LoginPageView.as_view(login_page='login-index.html'), name='login_page'),
    path('forgotpass/', ForgotPassView.as_view(), name='forgotpassword'),
    path('dashboard/', DashboardView.as_view(), name='dashboard_page'),
    path('upload/', UploadView.as_view(), name='upload_data'),
    path('register/', register_user, name='register_user'),
    path('test/', TestView.as_view(), name='test_data'),
    path('get-student-data/<str:student_id>/', get_student_data, name='get_student_data'),
]

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signature/pasign/app/models.py
from django.db import models
import os

def get_user_signature_path(instance, filename):
    """
        Creates a folder for each user using their student_id

        Example:
        >>> instance = UserData(student_id='1234567890')
        >>> get_user_signature_path(instance, 'signature_1.png')
        'Student 1234567890/signature_1.png'
        >>> get_user_signature_path(instance, 'signature_2.png')
        'Student 1234567890/signature_2.png'
        >>> get_user_signature_path(instance, 'signature_3.png')
        'Student 1234567890/signature_3.png'
    """
    folder_name = f"Student {instance.student_id}"
    return os.path.join(folder_name, filename)

class UserData(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    student_id = models.CharField(max_length=15)
    email = models.EmailField()
    signature_1 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_2 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)
    signature_3 = models.FileField(upload_to=get_user_signature_path, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

signature/pasign/app/forms.py
from django import forms
from .models import UserData

class UserDataForm(forms.ModelForm):
    class Meta:
        model = UserData
        fields = ['first_name', 'last_name', 'student_id', 'email']

signature/pasign/app/views.py
import os
from django.views import View
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import UserDataForm
from django.http import JsonResponse
from .models import UserData, get_user_signature_path
from django.contrib import messages
from django.conf import settings

# LANDING PAGE
class LandingPageView(View):
    landing_page = 'index.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.landing_page)

# LOGIN
class LoginPageView(View):
    login_page = 'landing/login-index.html'

    def get(self, request):
        return render(request, self.login_page)

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')  # Check if the checkbox is checked

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            if not remember_me:
                # If "Remember Me" is not checked, set session expiry to 0 (browser session)
                request.session.set_expiry(0)

            return redirect('dashboard_page')  # Replace with the actual URL name for your dashboard page
        else:
            # Authentication failed, handle accordingly (e.g., show an error message)
            pass

        return render(request, self.login_page)
        
# FORGOT PASSWORD
class ForgotPassView(View):
    forgotpassword = 'forgotpass.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.forgotpassword)

# DASHBOARD
class DashboardView(View):
    dashboard_page = 'dashboard.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.dashboard_page)
    
# UPLOAD
class UploadView(View):
    upload_data = 'upload.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.upload_data)
    
# REGISTER STUDENT
def register_user(request):
    if request.method == 'POST':
        form = UserDataForm(request.POST, request.FILES)

        signatures = request.FILES.getlist('signature_files')

        if form.is_valid() and len(signatures) == 3:
            # Check for existing user with case-insensitive comparison
            student_id = form.cleaned_data['student_id']
            email = form.cleaned_data['email'].lower()

            # Check if a user with the same student ID or email already exists
            if UserData.objects.filter(student_id=student_id).exclude(id=form.instance.id).exists() or \
               UserData.objects.filter(email__iexact=email).exclude(id=form.instance.id).exists():
                messages.error(request, 'User with similar information already exists. Please check and try again.')
                return render(request, 'upload.html', {'form': form})

            user_data = form.save()

            # Use the get_user_signature_path function to determine the path
            signature_folder = get_user_signature_path(user_data, '')


            for i, signature_file in enumerate(signatures, start=1):
                file_extension = os.path.splitext(signature_file.name)[1]
                new_file_name = f'{student_id}_signature_{i}{file_extension}'
                new_file_path = os.path.join(settings.MEDIA_ROOT, signature_folder, new_file_name)
                
                os.makedirs(os.path.dirname(new_file_path), exist_ok=True)

                with open(new_file_path, 'wb') as file:
                    file.write(signature_file.read())
                
                setattr(user_data, f'signature_{i}', os.path.join(signature_folder, new_file_name))

            user_data.save()

            # Add success message
            messages.success(request, 'Registration successful!')

            return redirect('upload_data')  # Redirect after successful registration

    else:
        form = UserDataForm()

    return render(request, 'upload.html', {'form': form})


# TEST
class TestView(View):
    test_data = 'test.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.test_data)

def get_student_data(request, student_id):
    try:
        student = UserData.objects.get(student_id=student_id)
        data = {
            'name': f"{student.first_name} {student.last_name}",
            'email': student.email,
            'signature_1_url': student.signature_1.url if student.signature_1 else '',
            'signature_2_url': student.signature_2.url if student.signature_2 else '',
            'signature_3_url': student.signature_3.url if student.signature_3 else '',
        }
        return JsonResponse(data)
    except UserData.DoesNotExist:
        return JsonResponse({'error': 'Student not found'}, status=404)



    

    

signature/pasign/app/templates/dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}">

    <title>Dashboard</title>
    
    <!DOCTYPE html>

</head>
<body>
        
    <div class="navigation">
        <a class="button" href="{% url 'landing_page' %}">
            <img src="{% static 'dashboard/CS.png' %}">
            <div class="logout">LOGOUT</div>
        </a>
    </div>

    <div class="container">
        <button type="button" class="btn cube cube-hover" id="uploadButton">
            <div class="bg-top">
                <div class="bg-inner"></div>
            </div>
            <div class="bg-right">
                <div class="bg-inner"></div>
            </div>
            <div class="bg">
                <div class="bg-inner"></div>
            </div>
            <div class="text">UPLOAD DATA</div>
        </button>

        <button type="button" class="btn cube cube-hover" id="testButton">
            <div class="bg-top">
                <div class="bg-inner"></div>
            </div>
            <div class="bg-right">
                <div class="bg-inner"></div>
            </div>
            <div class="bg">
                <div class="bg-inner"></div>
            </div>
            <div class="text">TEST DATA</div>
        </button>
    </div>



    <script>
        document.getElementById("uploadButton").addEventListener("click", function () {
            window.location.href = "{% url 'upload_data' %}";
        });

        document.getElementById("testButton").addEventListener("click", function () {
            window.location.href = "{% url 'test_data' %}";
        });
    </script>


<script src="{% static 'dashboard/dashboard.js' %}"></script>

</body>
</html>

signature/pasign/app/templates/forgotpass.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Forgot Password</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'forgotpass/css/forgotpass.css' %}">

</head>
<body>

<section class="ftco-section">
    <div class="top-gradient"></div>
  <div class="bottom-gradient"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    <div class="form-group text-center">
                        <a href="{% url 'login_page' %}" class="btn btn-secondary">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>                    
                    <div class="img" style="background-image: url(images/log.gif);"></div>
                    <div class="login-wrap p-4 p-md-5">
                        <div class="d-flex">
                            <div class="w-100">
                                <h3 class="mb-4" style="text-align: center;">PASIGN</h3>
                            </div>
                        </div>
                        <form action="#" class="signin-form">
                            <div class="form-group text-center mb-3">
                                <p>No problem, we’ll email you instructions to reset your password.</p>
                            </div>
                            <div class="form-group mb-3 text-center">
                                <label class="label" for="email"></label>
                                <input type="email" class="form-control" placeholder="Enter your Corporate Email" required>
                            </div>
                            <div class="form-group text-center">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3">Reset Password</button>
                            </div>
                        </form>
                        <div class="form-group text-center">
                            <a href="{% url 'login_page' %}" class="btn btn-link btn-no-hover">
                                <span style="font-size: 24px; cursor: pointer;">&larr;</span> Back to Login
                            </a>
                        </div>                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="js/jquery.min.js"></script>
<script src="js/popper.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/main.js"></script>

</body>
</html>

signature/pasign/app/templates/login-index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'login/css/login.css' %}">

</head>
<body>

<section class="ftco-section">
    <div class="top-gradient"></div>
    <div class="bottom-gradient"></div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="wrap d-md-flex">
                    <div class="form-group text-center">
                        <a href="{% url 'landing_page' %}" class="btn btn-secondary">
                            <i class="fa fa-arrow-left"></i>
                        </a>
                    </div>                    
                    <!-- app/templates/app/landing/index.html -->
                    <div class="img background-image"></div>
                    <div class="login-wrap p-4 p-md-5">
                        <div class="d-flex">
                            <div class="w-100">
                                <h3 class="mb-4" style="text-align: center;">PASIGN</h3>
                            </div>
                        </div>
                        <!-- LOGIN PART -->
                        <form action="{% url 'login_page' %}" method="post" class="signin-form">
                            {% csrf_token %}
                            {% if error_message %}
                                <div class="alert alert-danger" role="alert" style="font-size: 14px;">
                                    {{ error_message }}
                                </div>
                            {% endif %}
                            <div class="form-group mb-3">
                                <label class="label" for="name">Username</label>
                                <input type="text" name="username" class="form-control" placeholder="Username" required>
                            </div>
                            <div class="form-group mb-3">
                                <label class="label" for="password">Password</label>
                                <input type="password" name="password" class="form-control" placeholder="Password" required>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary rounded submit px-3" id="loginButton">Login</button>
                            </div>
                            
                            <div class="form-group d-md-flex">
                                <div class="w-50 text-left">
                                    <label class="checkbox-wrap checkbox-primary mb-0">Remember Me
                                        <input type="checkbox" name="remember_me" {% if request.COOKIES.remember_me %}checked{% endif %}>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'forgotpassword' %}">Forgot Password?</a>
                                </div>
                            </div>
                        </form>
      
                        <div class="form-group text-center">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'login/js/jquery.min.js' %}"></script>
<script src="{% static 'login/js/popper.js' %}"></script>
<script src="{% static 'login/js/bootstrap.min.js' %}"></script>
<script src="{% static 'login/js/login.js' %}"></script>


</body>
</html>

signature/pasign/app/templates/test.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'test/test.css' %}">
    <title>Test Data</title>
</head>
<body>

<main class="demo-page-content">
    <section>
        <div class="row">
            <div class="column">
                <div class="href-target" id="input-types"></div>
                <h1>
                    TEST SIGNATURE
                </h1>
                <p>Input Data & Signatures to Test</p>
            </div>

            <a href="{% url 'dashboard_page' %}" style="text-decoration:none">
                <div class="container1">
                    <button class="button1">
                        <div class="flex-container">
                            <div class="text1">
                                Back
                            </div>

                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up"
                                 width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                 stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1"/>
                            </svg>
                        </div>
                    </button>
                </div>
            </a>
        </div>

        <div class="container">
            <div class="info-container">
                <div class="nice-form-group">
                    <label>Enter Student ID Number</label>
                    <input type="text" id="studentIdInput" placeholder="0000-0-0000" value="" />
                </div> 
                
                <div class="nice-form-group">
                    <label>Name</label>
                    <input type="text" id="nameInput" placeholder="" value="" disabled />
                </div>
                
                <div class="nice-form-group">
                    <label>Corporate Email</label>
                    <input type="text" id="emailInput" placeholder="" value="" disabled />
                </div>

                <br>

            </div>

                <!-- PREVIEW IMAGE -->

            <div class="test-container">

                <div class="signature-container">
                  <div class="info-container1">
                    <div class="nice-form-group">
    
                        <form runat="server">
                            <div class="image-preview1">
                                <img id="blah1" src="" alt="" />
                            </div>
                        </form>
    
                        <form runat="server">
                            <div class="image-preview1">
                                <img id="blah2" src="" alt="" />
                            </div>
                        </form>
    
                        <form runat="server">
                            <div class="image-preview1">
                                <img id="blah3" src="" alt="" />
                            </div>
                        </form>  
                      
                    </div>
                  </div>
    
                  
                  <a class="btn" href="#">TEST</a>
    
                  <div class="info-container">
                    <div class="nice-form-group">
    
                      <form runat="server">
                        <div class="image-preview">
                          <img id="blah4" src="#" alt="Your Signature Preview" />
                        </div>
                        <label for="imgInp4" class="custom-file-upload">
                            Choose Image
                            <input accept="image/*" type='file' id="imgInp4" style="display: none;" />
                          </label>                          
                      </form>
                      
                    </div>
                  </div>
                </div>
  
  
                <div class="result-container">
                  <table class="result-table">
                      <tr>
                          <td class="result-tab">
                              <h3>Result 1: 80%</h3>
                          </td>
                          <td class="result-tab">
                              <h3>Result 2: 75%</h3>
                          </td>
                          <td class="result-tab">
                              <h3>Result 3: 90%</h3>
                          </td>
                          <td class="result-tab">
                              <h3>Average Result: 81%</h3>
                          </td>
                      </tr>
                  </table>
              </div>
        </div>
    </section>

    <script>
        document.getElementById('imgInp4').onchange = evt => {
            const fileInput = evt.target;
            const [file] = fileInput.files;
    
            if (file) {
                const previewImage = document.getElementById('blah4');
                previewImage.src = URL.createObjectURL(file);
            }
        };
    

    // Event listener for student ID input
    document.getElementById('studentIdInput').addEventListener('input', function () {
        let studentId = this.value.trim(); // Trim any leading or trailing whitespaces

        // Remove existing hyphens
        studentId = studentId.replace(/-/g, '');

        // Insert hyphens at the correct positions
        if (studentId.length >= 4) {
            studentId = studentId.substring(0, 4) + '-' + studentId.substring(4, 5) + '-' + studentId.substring(5, 9);
        }

        // Update the input field with the formatted studentId
        this.value = studentId;

        if (studentId.length === 11) { // Check if the full pattern is matched
            // Make an AJAX request to the server to fetch corresponding name, email, and signature file URLs
            fetch(`/get-student-data/${encodeURIComponent(studentId)}/`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error(`HTTP error! Status: ${response.status}`);
                    }
                    return response.json();
                })
                .then(data => {
                    console.log(data); // Log the data to the console for debugging

                    document.getElementById('nameInput').value = data.name || '';
                    document.getElementById('emailInput').value = data.email || '';

                    // Assuming you have elements with IDs 'blah1', 'blah2', 'blah3' to display the images
                    for (let i = 1; i <= 3; i++) {
                        const imagePreview = document.getElementById(`blah${i}`);
                        const signatureFieldKey = `signature_${i}_url`;
                        
                        if (data[signatureFieldKey]) {
                            // Do not include '/media/' again; it's already in the data[signatureFieldKey]
                            imagePreview.src = data[signatureFieldKey];
                            imagePreview.style.display = 'block'; // Show the image preview element
                        } else {
                            imagePreview.src = ''; // Clear the image preview element
                            imagePreview.style.display = 'none'; // Hide the image preview element
                        }
                    }
                })
                .catch(error => {
                    console.error('Error fetching student data:', error);
                    // Handle the error, e.g., display a message to the user
                });
        } else {
            // Clear name, email, and image previews if the pattern is not fully matched
            document.getElementById('nameInput').value = '';
            document.getElementById('emailInput').value = '';
            for (let i = 1; i <= 3; i++) {
                document.getElementById(`blah${i}`).src = ''; // Clear the image preview element
                document.getElementById(`blah${i}`).style.display = 'none'; // Hide the image preview element
            }
        }
    });
    </script>
</main>

</body>
</html>

signature/pasign/app/templates/upload.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Upload Data</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
  <link rel="stylesheet" href="{% static 'upload/upload.css' %}">
</head>
<body>
  
  <main class="demo-page-content">  
    <section>
      <div class="row">
        <div class="column">
          <div class="href-target" id="input-types"></div>
          <h1>REGISTER SIGNATURE</h1>
          <p>Input Data & Signatures</p>
        </div>

        <a href="{% url 'dashboard_page' %}" style="text-decoration:none">
          <div class="container1">
            <button class="button1">
              <div class="flex-container">
                <div class="text1">
                  Back
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-back-up" 
                     width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" 
                     stroke-linecap="round" stroke-linejoin="round">
                  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                  <path d="M9 13l-4 -4l4 -4m-4 4h11a4 4 0 0 1 0 8h-1" />
                </svg>
              </div>
            </button>
          </div>
        </a>
      </div>

        <form action="{% url 'register_user' %}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
      
          <div class="name-container">
              <div class="nice-form-group">
                  <label for="id_first_name">First Name</label>
                  <input type="text" id="id_first_name" name="first_name" placeholder="Your firstname" required />
              </div>
      
              <div class="nice-form-group">
                  <label for="id_last_name">Last Name</label>
                  <input type="text" id="id_last_name" name="last_name" placeholder="Your lastname" required />
              </div>
          </div>
      
          <div class="nice-form-group">
              <label for="id_student_id">Student ID Number</label>
              <input type="text" id="id_student_id" name="student_id" placeholder="0000-0-0000" required />
          </div>
      
          <div class="nice-form-group">
              <label for="id_email">Email</label>
              <input type="email" id="id_email" name="email" placeholder="0000-0-0000@psu.palawan.edu.ph" required />
          </div>
      
          <!-- <div class="nice-form-group">
              <label for="id_signature_type">Select Signature Type</label>
              <select id="id_signature_type" name="signature_type" required>
                  <option disabled selected>Please select a signature type</option>
                  <option>Current Signature</option>
                  <option>Old Signature</option>
              </select>
          </div> -->
      
          <div class="nice-form-group">
              <label for="id_signature_files">File upload</label>
              <input type="file" accept="image/*" id="id_signature_files" name="signature_files" multiple required />
          </div>
      
          <br>

          {% if messages %}
                {% for message in messages %}
                    <div id="success-message" class="alert alert-success text-center" role="alert" style="color: green;">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
      
          <div class="container">
              <button class="button" type="submit">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                      <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75"></path>
                  </svg>
                  <div class="text">
                      Submit
                  </div>
              </button>
          </div>
      </form>
    </section>
  </main>

  <script src="{% static 'upload/upload.js' %}"></script>
</body>
</html>